version: "3.7"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: bash -c "
      psql -U mlflow -c 'CREATE EXTENSION IF NOT EXISTS postgis;' &&
      psql -U mlflow -c 'CREATE EXTENSION IF NOT EXISTS postgis_topology;'
  mlflow-server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres:5432/mlflow
      MLFLOW_DEFAULT_ARTIFACT_ROOT: ./mlruns
    command: mlflow server --backend-store-uri $MLFLOW_BACKEND_STORE_URI --default-artifact-root $MLFLOW_DEFAULT_ARTIFACT_ROOT --host 0.0.0.0 --port 5000

volumes:
  postgres_data:
